### ISSUE TITLE
训练300轮，结果是纯黑色

### ISSUE THREAD

**Issue by YaoXingbo** [chairc/Integrated-Design-Diffusion-Model#101]
作者您好，您的文章写得很棒
我在实验过程中换成了自己的数据集，但是train出来是纯黑色，这是为什么
我的数据集是尺寸不固定的长方形图像（建筑物外观图）

为了debug代码，我下载了您的预训练模型，可以generate出来图像，但是我自己训练的ckpt生成的是纯黑的

<img width="445" alt="image" src="https://github.com/user-attachments/assets/8f1bdd01-d7d8-47e8-9629-a19a4614920c">

**Comment by chairc** [comment]
你的训练参数可否发一下？

**Comment by YaoXingbo** [comment]
谢谢作者的回复，我刚刚用您的demo_dataset训练了100轮，能出现颜色

自己的数据集却不行，感觉是数据集的问题？我的数据集只有一个class_1, 数据集我发到群里了，作者可以帮忙看看嘛


  Input params: Namespace(seed=0, conditional=False, sample='ddpm', network='unetv2', run_name='HighDataset_exp2', epochs=100, batch_size=16, num_workers=0, image_size=64, dataset_path='./datasets/HighDataset', amp=False, optim='adamw', loss='mse', act='gelu', lr=0.0003, lr_func='linear', result_path='./results', save_model_interval=False, save_model_interval_epochs=10, start_model_interval=-1, vis=False, num_vis=-1, image_format='png', noise_schedule='linear', resume=False, start_epoch=None, pretrain=False, pretrain_path='./results/cifar10-64-weight.pt', use_gpu=0, distributed=False, main_gpu=0, world_size=2, cfg_scale=3)
