### ISSUE TITLE
可以用来生成工业上的缺陷图片吗？

### ISSUE THREAD

**Issue by leemayi** [chairc/Integrated-Design-Diffusion-Model#17]

**Comment by chairc** [comment]
可以，但是目前使用DDPM和DDIM需要足够大的显存，后续发布LDM可节约显存

**Comment by tangwy98** [comment]
> 可以，但是目前使用DDPM和DDIM需要足够大的显存，后续发布LDM可节约显存

期待LDM

**Comment by andikeke1223** [comment]
请问可以生成彩色的缺陷图片吗？想从彩色原图中把划痕，污染，异物这种不良剪切出来进行生成类似的不良。

**Comment by chairc** [comment]
> 请问可以生成彩色的缺陷图片吗？想从彩色原图中把划痕，污染，异物这种不良剪切出来进行生成类似的不良。

可以生成彩色的
