### ISSUE TITLE
数据集是否需要划分

### ISSUE THREAD

**Issue by zhongsir771** [chairc/Integrated-Design-Diffusion-Model#3]
作者你好，小白想问一下，生成和训练的数据集是否要想训练其他神经网络一样划分数据集呀？

**Comment by chairc** [comment]
仅类别划分就行，比如狗的放一个文件夹，猫的放一个文件夹，一个类别放一个文件夹就可以。不用划分训练集和验证集。生成都是随机的，全靠肉眼看👀

**Comment by zhongsir771** [comment]
好的，谢谢作者！还想咨询一个问题就是我跑了代码，但是我发现只能跑64X64分辨率的，如果我想跑其他分辨率的图片请问要如何修改代码呢？


| |
钟浩
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yu ***@***.***> |
| 发送日期 | 2023年9月28日 10:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chairc/Industrial-Defect-Diffusion-Model] 数据集是否需要划分 (Issue #3) |

仅类别划分就行，比如狗的放一个文件夹，猫的放一个文件夹，一个类别放一个文件夹就可以。不用划分训练集和验证集。生成都是随机的，全靠肉眼看👀

**Comment by chairc** [comment]
修改image_size为32的倍数

**Comment by chairc** [comment]
> 好的，谢谢作者！还想咨询一个问题就是我跑了代码，但是我发现只能跑64X64分辨率的，如果我想跑其他分辨率的图片请问要如何修改代码呢？
> 
> 
> | |
> 钟浩
> |
> |
> ***@***.***
> |
> ---- 回复的原邮件 ----
> | 发件人 | Yu ***@***.***> |
> | 发送日期 | 2023年9月28日 10:25 |
> | 收件人 | ***@***.***> |
> | 抄送人 | ***@***.***> ,
> ***@***.***> |
> | 主题 | Re: [chairc/Industrial-Defect-Diffusion-Model] 数据集是否需要划分 (Issue #3) |
> 
> 仅类别划分就行，比如狗的放一个文件夹，猫的放一个文件夹，一个类别放一个文件夹就可以。不用划分训练集和验证集。生成都是随机的，全靠肉眼看👀
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

现在的网络为标准的unet网络，参数较大，如果显存允许可以跑更大尺寸，例如40GB显存可以跑128的，后期的话我会升级网络结构，使用参数量更小的模型

**Comment by zhongsir771** [comment]
oo,好的，谢谢！


在2023年10月2日 17:18，Yu ***@***.***> 写道：

修改image_size为32的倍数
