### ISSUE TITLE
输入的是灰度图像 能输出灰度图像吗

### ISSUE THREAD

**Issue by Cherish420** [chairc/Integrated-Design-Diffusion-Model#32]
大佬  我是用此模型来生成图像，输入是灰度图，在训练后 也能生成灰度图像吗？ 我跑了200epoch 后生成的是彩色图像

**Comment by chairc** [comment]
模型设置的输入是3通道，如果你要练灰度图可能得自己修改源代码

**Comment by chairc** [comment]
找到/model/networks中所有代码的`def __init__(self, in_channel=3, out_channel=3, channel=None, time_channel=256, num_classes=None, image_size=64, device="cpu", act="silu"):`，吧`in_channel`和`out_channel`设置为1就行

**Comment by Cherish420** [comment]
感谢博主 我也看到这块代码 现在在尝试修改。
