### ISSUE TITLE
租用的GPU训练时出现socket has failed to listen on any local network address

### ISSUE THREAD

**Issue by egoist945402376** [chairc/Integrated-Design-Diffusion-Model#40]
<img width="1187" alt="微信图片_20240202103544" src="https://github.com/chairc/Integrated-Design-Diffusion-Model/assets/116807701/b818a9b6-81b2-473d-a3a3-55336e2fce96">
请问有什么头绪吗, 谢谢大佬的解答.

**Comment by chairc** [comment]
12345这个地址已经被使用了，你可以在这里[修改端口](https://github.com/chairc/Integrated-Design-Diffusion-Model/blob/6b0f72ec369c212f59f769ac5315cb729a3722f1/tools/train.py#L76C13-L77C13)
![image](https://github.com/chairc/Integrated-Design-Diffusion-Model/assets/43342212/3bee2836-9e69-447a-b97f-e7c438331b2d)
