### ISSUE TITLE
請問支援prompt輸入嗎?

### ISSUE THREAD

**Issue by p890040** [chairc/Integrated-Design-Diffusion-Model#47]
您好 首先感謝作者傑出的作品
我注意到你們conditional的條件是用類別來區分，不同於一般diffusion模型用text
且你們的模型輸入時也沒有prompt輸入

想請問你們的做法跟一般diffusion的差異 謝謝

**Comment by chairc** [comment]
这是基础的扩散模型算法，不涉及到提示词prompt的输入。
