### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by lzh1998-jansen** [chairc/Integrated-Design-Diffusion-Model#5]
由于我的业务领域数据集比较难收集，所以我看了看ddpm，来生成图像数据集。但是看了看，感觉不太现实，生成质量和计算资源都比较难处理

**Comment by chairc** [comment]
你可以考虑一下stable-diffusion，那个开源生成模型支持多种sample😃

**Comment by chairc** [comment]
类别就是可以生成不同的图片，训练时按照类别训练，生成时按照类别生成图片。

**Comment by lzh1998-jansen** [comment]
了解了，感谢~！
