### ISSUE TITLE
关于训练集和验证集

### ISSUE THREAD

**Issue by lixudong741** [chairc/Integrated-Design-Diffusion-Model#50]
在训练文件下，
parser.add_argument("--train_dataset_path", type=str,
                        default="G:/diffusion/Integrated-Design-Diffusion-Model-main/datasets/dataset_demo/class_1")
    parser.add_argument("--val_dataset_path", type=str,
                        default="G:/diffusion/Integrated-Design-Diffusion-Model-main/datasets/dataset_demo/class_2")
    # Enable automatic mixed precision training (needed)
我在训练集和验证集放入不同的图片，但是训练出来的图片总是和验证集一模一样，请问这是什么原因？

训练集不起作用，而且生成的图片，不同的轮次的高清hr图片跟原本验证集图片一样，但是可以看到训练过程中还有损失比如MSE=0.00471  求解答

**Comment by chairc** [comment]
sr文件夹中的是超分模型训练，是把低清晰度的图通过卷积神经网络恢复为高清晰度的。
扩散模型训练[参考](https://github.com/chairc/Integrated-Design-Diffusion-Model/blob/v1.1.3/tools/train.py)

**Comment by lixudong741** [comment]
好的好的 谢谢 我的问题
