### ISSUE TITLE
生成出来的图片是噪点图

### ISSUE THREAD

**Issue by LinHoujie** [chairc/Integrated-Design-Diffusion-Model#7]
![df](https://github.com/chairc/Industrial-Defect-Diffusion-Model/assets/132760640/5580b0bc-e8dd-48fc-9a85-de24b3f276ee)
用的ddpm，训练的参数和生成的参数都是一样的，生成出来的是噪点图，想问下是哪部分出现了问题呢

**Comment by chairc** [comment]
能把参数设置信息发一下吗？每次训练的时候会有一个train.txt文件

**Comment by chairc** [comment]
这种问题的出现大多数为激活函数设置的与训练不符

**Comment by chairc** [comment]
![image](https://github.com/chairc/Industrial-Defect-Diffusion-Model/assets/43342212/cc458dee-ea88-4d07-8e2d-10185382d5ce)

**Comment by chairc** [comment]
加一下群，我们群里交流，949120343

**Comment by LinHoujie** [comment]
好的
