### ISSUE TITLE
关于test_module.py

### ISSUE THREAD

**Issue by yunjiefeng123** [chairc/Integrated-Design-Diffusion-Model#74]
尊敬的作者您好，我想问一下关于test_module.py的参数是如何设置的，里边的test.pt是从哪里生成的，应该如何操作获取

**Comment by chairc** [comment]
test_module.py是跑单元测试、集成测试的，一般用不到。要跑评估就用[FID_calculator.py](https://github.com/chairc/Integrated-Design-Diffusion-Model/blob/main/tools/FID_calculator.py)或者[FID_calculator_plus.py](https://github.com/chairc/Integrated-Design-Diffusion-Model/blob/main/tools/FID_calculator_plus.py)

**Comment by yunjiefeng123** [comment]
那就是说我其实不用管就可以了么？我是小白，但是我毕业论文想做这个，所以我想问清楚一点，打扰了，谢谢您

**Comment by chairc** [comment]
不用管test_module，你只用关注tools、model文件夹的东西就可以了

**Comment by yunjiefeng123** [comment]
好的，谢谢，感激
