### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 4C4247** [chairc/Integrated-Design-Diffusion-Model#84]
使用DDPM来进行训练，train.py和generate.py里面的参数要保持一致吗？generate.py的results_path可以不设置吗？

**Comment by 4C4247** [comment]
开始跑了，tools里面的train，跑了一轮之后，没有在vis里面输出任何图片，是怎么回事呢。generate.py要设置为........../results/vis这样子才能跑一轮出来图片吗？刚刚入门请教一下~谢谢佬

**Comment by chairc** [comment]
> 开始跑了，tools里面的train，跑了一轮之后，没有在vis里面输出任何图片，是怎么回事呢。generate.py要设置为........../results/vis这样子才能跑一轮出来图片吗？刚刚入门请教一下~谢谢佬

--vis可以显示每一轮生成的图片
