### ISSUE TITLE
跑了十轮生成出来的样本五花八门正常不

### ISSUE THREAD

**Issue by 4C4247** [chairc/Integrated-Design-Diffusion-Model#85]
![ddpm_lbg_240806](https://github.com/user-attachments/assets/dfea17da-2bf2-4f84-b160-39cefcf2ab00)

**Comment by chairc** [comment]
10轮不足以训练你想要的结果，建议300~500轮

**Comment by 4C4247** [comment]
> 10轮不足以训练你想要的结果，建议300~500轮

好的明白啦，谢谢~
