### ISSUE TITLE
训练DDPM生成vis为噪声图

### ISSUE THREAD

**Issue by bye111** [chairc/Integrated-Design-Diffusion-Model#94]
请问使用自带的三类别dataset_demo训练后可视化结果为什么都是噪声图：
![image](https://github.com/user-attachments/assets/ca0db7d5-9901-4e7a-abce-e3f2a9022752)
还有请问生成的ema和ckpt两种训练结果有什么不同
配置文件如下：
Namespace(seed=0, conditional=True, sample='ddpm', network='unet', run_name='df', epochs=50, batch_size=2, num_workers=0, image_size=64, dataset_path='../datasets/dataset_demo/', amp=False, optim='adamw', loss='mse', act='gelu', lr=0.0003, lr_func='linear', result_path='../results', save_model_interval=False, save_model_interval_epochs=10, start_model_interval=-1, vis=True, num_vis=-1, image_format='png', noise_schedule='linear', resume=False, start_epoch=None, pretrain=False, pretrain_path='', use_gpu=0, distributed=False, main_gpu=0, world_size=2, cfg_scale=3)

**Comment by chairc** [comment]
多练一百轮就有形状了，你可以使用预训练模型加快训练

**Comment by bye111** [comment]
好的 谢谢您
